# Generated by Django 3.1.7 on 2021-03-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210302_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_photo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
